services:
  frp-panel:
    build: .
    container_name: frp-panel
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./conf.d:/app/conf.d
      - ./frpc.toml:/app/frpc.toml:ro
    env_file:
      - .env
